# Generated by Django 5.0.6 on 2024-06-27 09:47

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=20, max_length=20, prefix='', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=256)),
                ('frame_width', models.PositiveSmallIntegerField()),
                ('frame_height', models.PositiveSmallIntegerField()),
                ('fps', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('background_color', models.CharField(max_length=16)),
                ('font', models.PositiveSmallIntegerField()),
                ('font_scale', models.PositiveSmallIntegerField()),
                ('font_thickness', models.PositiveSmallIntegerField()),
                ('font_color', models.CharField(max_length=16)),
                ('file_path', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=32)),
                ('file_extension', models.CharField(default='mp4', max_length=16)),
            ],
        ),
    ]
